### ISSUE TITLE
Artees.UnitySemVer.Tests asmdef has incorrect name

### ISSUE THREAD

**Issue by Thundernerd** [Artees/Unity-SemVer#1]
The asmdef for the tests is named `Tests`  and should match the file name `Artees.UnitySemVer.Tests`.

This might conflict with other existing packages since `Tests` is a very generic name.

![image](https://user-images.githubusercontent.com/5531467/104163179-42a37180-53f6-11eb-87d3-e6b4b87792c9.png)

**Comment by Artees** [comment]
renamed
