### ISSUE TITLE
SemVerDrawer - Recursive FoldoutGroup Label Rendering

### ISSUE THREAD

**Issue by GDGRhinox** [Artees/Unity-SemVer#3]
We added the following field to a ScriptableObject class as per the documentation:
```
 [SemVer] string Version = "0.0.0";
```
However the drawer yielded the following result:
![image](https://user-images.githubusercontent.com/80831813/140514205-576ec727-9d66-437e-ad63-8aa71ae1e3d6.png)

Upon checking the code in **Artees/UnitySemVer/Editor/SemVerDrawer.cs** at line 38:
```
*35*        protected SemVer DrawSemVer(Rect position, SerializedProperty property, GUIContent label)
*36*        {
*37*            InitPosition(position);
*38*            label.text = $"{label.text} {Target}";
*39*            property.isExpanded =
```
The culprit seems to be **label.text** recursively prefixes itself on each Draw call.
Is there some prefix which should be kept here or can we fix it by changing it to: 
```
 label.text = $"{Target}";
```

**Comment by Artees** [comment]
I can't reproduce the issue, but the PR should work.
